### ISSUE TITLE
Disable merge commits

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-common-grpc#41]
By default in this repo, PRs are using merge commits.  Squash and merge is almost always the right answer.  So two thoughts:

1. Could someone with admin disable naked merge commits on the repo?

2. Do we have a way to set this broadly across all of googleapis?

3. @jonparrott what are your thoughts?  Do you have a preference here?

**Comment by JustinBeckwith** [comment]
cc @googleapis/node-team

**Comment by jonparrott** [comment]
It is done.
