### ISSUE TITLE
Start testing gRPC-js

### ISSUE THREAD

**Issue by kjin** [googleapis/nodejs-common-grpc#67]
We should explore ways to start testing gRPC-js against this repo, [gax-nodejs](https://github.com/googleapis/gax-nodejs), and all dependent client libraries.

Here is a proposal for doing so (using this repo as an example):

- Create a branch `grpc-js` even with `master`
- In this branch, make a single commit that changes files enough to force `@grpc/js` to be used
- Add a new Circle CI job that runs the usual tests on Node 8, with an additional prefixed step that rebases the current PR on `grpc-js` (which should effectively just inject the one commit)
- If this breaks (and it shouldn't break often), rebase `grpc-js` on `master` and fix merge conflicts

Essentially, `grpc-js` should always be behind/even with `master`, with one extra commit that changes things just enough for `@grpc/js` to be used instead of `grpc`.

What are the changes needed in this one commit?

- Replace dependency on `grpc` with `@grpc/js` in `package.json`
- Add a pre-require hook (similar to [this](https://github.com/grpc/grpc-node/blob/master/test/client-libraries-integration/use-grpc-js.js), but without the extra monkeypatching of `google-gax` and `@google-cloud/common-grpc`)
- Modify npm test scripts to insert this pre-require hook

The goal here is to be as un-intrusive (in source modification) as possible. Thoughts?

/cc @ofrobots @murgatroid99 @JustinBeckwith @googleapis/node-team

**Comment by JustinBeckwith** [comment]
This is actually rolling out this week!

**Comment by kjin** [comment]
Awesome, thanks for all the work!
